/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    CoverMusic: typeof import('./src/components/CoverMusic.vue')['default']
    DailyQuote: typeof import('./src/components/DailyQuote.vue')['default']
    ImageGrid: typeof import('./src/components/ImageGrid.vue')['default']
    LikeButton: typeof import('./src/components/LikeButton.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./src/components/SkeletonCard.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
    VideoGrid: typeof import('./src/components/VideoGrid.vue')['default']
    WeatherWidget: typeof import('./src/components/WeatherWidget.vue')['default']
  }
}
